### ISSUE TITLE
No /usr/share/java/jaxb-api.jar in 4.0.0

### ISSUE THREAD

**Issue by AdamWill** [jakartaee/jaxb-api#268]
I'm not sure whether this is considered a bug or not - just filing it to bring it to your attention to check.

The Fedora package builds of jaxb-api 2.3.3 included a `/usr/share/java/jaxb-api.jar` , which is a symlink to `glassfish-jaxb-api/jakarta.xml.bind-api.jar`, the real file. The Fedora package was today updated to a build of 4.0.0. This no longer has the symlink. I can see no change in the package spec file which would affect it, so it seems like the change must have been upstream.

This seems to have broken dogtag-pki, which in turn has broken [FreeIPA](https://www.freeipa.org), because dogtag-pki in turn [installs a symlink pointing to `/usr/share/java/jaxb-api.jar`](https://github.com/dogtagpki/pki/blob/100d334d99748898274b92db9af371e28341b7e6/base/common/CMakeLists.txt#L125). That command, in Fedora's builds at least, winds up creating a symlink `/usr/share/pki/server/common/lib/jaxb-api.jar` -> `/usr/share/java/jaxb-api.jar`, and now of course that symlink is broken.

If this is an intended change, I'll file a ticket on dogtag-pki to have it do something different. But I figured it might instead be oversight or error, and it may be still be intended to make the library available in this location.

**Comment by lukasj** [comment]
AFAIK this project has never been dealing with os specific installers and it has no plans to do so.

**Comment by AdamWill** [comment]
That seems quite dismissive? The "OS specific package" is just using something this project used to provide - an unversioned file in a specific place - and no longer does. The fact that it's an "OS specific package" doesn't seem particularly relevant.

In any case, the code is in dogtag-pki's upstream, there's nothing specific to Fedora there. I'd expect the `/usr/share/java` part might differ between distros, but ultimately dogtag-pki is, I think, always looking for this unversioned `jaxb-api.jar` file in "the Java directory", which jaxb-api previously installed but no longer does.

If the answer is "we intentionally removed that and projects that want to work with jaxb-api 4 shouldn't expect it to be there", that's fine. But I don't see what "os specific installers/packages" really has to do with anything?

**Comment by lukasj** [comment]
> That seems quite dismissive? The "OS specific package" is just using something this project used to provide - an unversioned file in a specific place -

No, that has never been true. A file produced by this project since its inception in ~ 2005 has been published to maven repository (initially maven 1 repo on the java.net) only.

> and no longer does. The fact that it's an "OS specific package" doesn't seem particularly relevant.

Why do you think this project is responsible for maintaining RPMs listed at https://rpmfind.net/linux/rpm2html/search.php?query=mvn(jakarta.xml.bind%3Ajakarta.xml.bind-api) or https://rpmfind.net/linux/rpm2html/search.php?query=mvn(javax.xml.bind%3Ajaxb-api) which are responsible for the creation of the links, docs etc and the file/symlink dogtag-pki and/or freeipa project expects? 


> In any case, the code is in dogtag-pki's upstream, there's nothing specific to Fedora there. I'd expect the `/usr/share/java` part might differ between distros, but ultimately dogtag-pki is, I think, always looking for this unversioned `jaxb-api.jar` file in "the Java directory", which jaxb-api previously installed but no longer does.
> 
> If the answer is "we intentionally removed that and projects that want to work with jaxb-api 4 shouldn't expect it to be there", that's fine. But I don't see what "os specific installers/packages" really has to do with anything?

the name of binary produced by this project was changed from jaxb-api.jar to jakarta.xml.bind-api.jar between versions 2.3.2 and 2.3.3. Nothing else has changed. What has not been produced, couldn't be removed. But someone else, ie some downstream consumer, could stop producing/maintaining rpms of course, but that is out of control of this project.

**Comment by lukasj** [comment]
no worries, glad to see we managed to resolve this in the end.
